version: '3.4'

services:
  livro-app:
    image: ${DOCKER_REGISTRY-}techchallenge2:1.0
    build: .
    ports: 
      - "8080:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Pass123@"
      ACCEPT_EULA: "Y"
    ports:
      - "1450:1433"